name: CI

on:
    workflow_dispatch:
    # pull_request:
    # push:
    #     branches:
    #         - "**"
    # release:
    #     types:
    #         - published

env:
    IMAGE: ${{ vars.NCR_REGISTRY }}/studyon

jobs:
    build-and-push:
        name: build and push
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Set up Docker buildx
              uses: docker/setup-buildx-action@v2

            - name: Login to NCR
              uses: docker/login-action@v2
              with:
                registry: ${{ vars.NCR_REGISTRY }}
                username: ${{ secrets.NCP_ACCESS_KEY }}
                password: ${{ secrets.NCP_SECRET_KEY }}

            - name: Get current timestamp
              id: timestamp
              run: echo "timestamp=$(date '+%s')" >> "$GITHUB_OUTPUT"

            - name: build-and-push
              if: startsWith(github.ref, 'refs/heads')
              uses: docker/build-push-action@v4
              with:
                context: .
                tags: "${{ env.IMAGE }}:${{ steps.timestamp.outputs.timestamp }}"
                push: true

            - name: build-and-push
              if: startsWith(github.ref, 'refs/tags')
              uses: docker/build-push-action@v4
              with:
                context: .
                tags: "${{ env.IMAGE }}:${{ github.event.release.tag_name }}"
                push: true